# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest',
            field=models.TextField(default='None'),
        ),
    ]
