# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='igem',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
