# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamID', models.IntegerField(unique=True)),
                ('Teamname', models.CharField(max_length=30)),
                ('Region', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('Track', models.CharField(max_length=30)),
                ('Section', models.CharField(max_length=30)),
                ('Size', models.IntegerField()),
                ('Status', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
                ('Wiki', models.CharField(max_length=100)),
                ('Medal', models.CharField(max_length=20)),
                ('Award', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Use_parts', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='name',
            new_name='Name',
        ),
    ]
