# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='Abstract',
            new_name='Description',
        ),
    ]
