# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0002_user_interest'),
        ('sdin', '0002_auto_20171026_0618'),
    ]

    operations = [
    ]
