# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0002_auto_20171018_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('URL', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='works',
            name='DefaultImg',
            field=models.URLField(default='static\\img\\Team_img\\none.jpg'),
        ),
        migrations.AddField(
            model_name='works',
            name='TeamImg',
            field=models.ManyToManyField(to='sdin.TeamImg'),
        ),
    ]
