# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0002_circuit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
