# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('sdin', '0003_auto_20170928_0256'), ('sdin', '0004_auto_20170928_0300'), ('sdin', '0005_auto_20170928_0306'), ('sdin', '0006_auto_20170928_0540')]

    dependencies = [
        ('sdin', '0002_circuit_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='works',
            name='Award',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='works',
            name='Country',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Medal',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='works',
            name='Name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='works',
            name='Region',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Section',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Teamname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Track',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Use_parts',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='works',
            name='Wiki',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='works',
            name='Award',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='works',
            name='Use_parts',
            field=models.CharField(max_length=5120),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='Name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='Name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
