# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0003_auto_20171019_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamimg',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='works',
            old_name='TeamImg',
            new_name='Img',
        ),
    ]
