# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0003_auto_20170928_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Award',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='works',
            name='Country',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Medal',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='works',
            name='Name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='works',
            name='Region',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Section',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Status',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Teamname',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Track',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='works',
            name='Use_parts',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='works',
            name='Wiki',
            field=models.CharField(max_length=128),
        ),
    ]
