# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0003_auto_20170928_0256_squashed_0006_auto_20170928_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubParts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='parts',
            name='Subparts',
        ),
        migrations.AddField(
            model_name='works',
            name='Chassis',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='works',
            name='Description',
            field=models.CharField(default='To be add', max_length=1000),
        ),
        migrations.AddField(
            model_name='works',
            name='Keywords',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='works',
            name='SimpleDescription',
            field=models.CharField(default='To be add', max_length=500),
        ),
        migrations.AddField(
            model_name='subparts',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_name', to='sdin.Parts'),
        ),
        migrations.AddField(
            model_name='subparts',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_name', to='sdin.Parts'),
        ),
    ]
