# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0004_auto_20170928_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Award',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='works',
            name='Use_parts',
            field=models.CharField(max_length=5120),
        ),
    ]
