# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0005_papers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='Journal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='papers',
            name='Title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
