# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0005_auto_20171013_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='IEF',
            field=models.FloatField(default=0.0),
        ),
    ]
