# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0005_auto_20170928_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='Name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='Name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
