# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0006_works_ief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Country',
            field=models.CharField(max_length=50),
        ),
    ]
