# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0007_auto_20171014_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='SimpleDescription',
            field=models.TextField(default='To be add'),
        ),
    ]
