# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0009_auto_20171021_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='DOI',
            field=models.CharField(default='', max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='teamimg',
            name='Name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
