# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0011_auto_20171022_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsInteract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InteractType', models.CharField(default='normal', max_length=10)),
                ('Score', models.IntegerField(default=0)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_part', to='sdin.Parts')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_part', to='sdin.Parts')),
            ],
        ),
    ]
