# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0012_auto_20171022_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('picture', models.URLField(null=True)),
                ('related', models.CharField(max_length=200, null=True)),
                ('yearRelation', models.CharField(max_length=200)),
                ('trackRelation', models.CharField(max_length=200)),
                ('medalRelation', models.CharField(max_length=200)),
                ('weightedRelated', models.CharField(max_length=200, null=True)),
                ('suggestedProject', models.CharField(max_length=200, null=True)),
                ('suggestedPart', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
