# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0012_partsinteract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='Safety',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='parts',
            name='Scores',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AlterField(
            model_name='partsinteract',
            name='Score',
            field=models.FloatField(default=-1.0),
        ),
    ]
