# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0014_auto_20171022_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
