# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0024_auto_20171022_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='suggestedPart',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='suggestedProject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='weightedRelated',
            field=models.TextField(null=True),
        ),
    ]
