# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0025_auto_20171022_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
