# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0027_auto_20171022_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitCombines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Father', to='sdin.Circuit')),
                ('Father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sons', to='sdin.CircuitParts')),
                ('Sons', models.ManyToManyField(to='sdin.CircuitParts')),
            ],
        ),
    ]
