# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0028_circuitcombines'),
        ('sdin', '0013_auto_20171023_0254'),
    ]

    operations = [
    ]
