# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0030_auto_20171023_1219'),
        ('sdin', '0029_merge_20171023_1247'),
    ]

    operations = [
    ]
