# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0031_merge_20171023_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='Circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sdin.Circuit'),
        ),
        migrations.AlterField(
            model_name='works',
            name='DefaultImg',
            field=models.URLField(default='static/img/Team_img/none.jpg'),
        ),
        migrations.AlterField(
            model_name='works',
            name='logo',
            field=models.URLField(default='static/img/Team_img/none.jpg'),
        ),
    ]
