# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdin', '0032_auto_20171024_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitdevices',
            name='X',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='circuitdevices',
            name='Y',
            field=models.IntegerField(default=0),
        ),
    ]
